// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ac_pointLogLik
double ac_pointLogLik(double map_dist, double max_table_dist, double min_table_dist, double error_sd);
RcppExport SEXP _Racmacs_ac_pointLogLik(SEXP map_distSEXP, SEXP max_table_distSEXP, SEXP min_table_distSEXP, SEXP error_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type map_dist(map_distSEXP);
    Rcpp::traits::input_parameter< double >::type max_table_dist(max_table_distSEXP);
    Rcpp::traits::input_parameter< double >::type min_table_dist(min_table_distSEXP);
    Rcpp::traits::input_parameter< double >::type error_sd(error_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_pointLogLik(map_dist, max_table_dist, min_table_dist, error_sd));
    return rcpp_result_gen;
END_RCPP
}
// ac_mapNegLogLik
double ac_mapNegLogLik(NumericVector map_dist, NumericVector max_table_dist, NumericVector min_table_dist, double error_sd);
RcppExport SEXP _Racmacs_ac_mapNegLogLik(SEXP map_distSEXP, SEXP max_table_distSEXP, SEXP min_table_distSEXP, SEXP error_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type map_dist(map_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type max_table_dist(max_table_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type min_table_dist(min_table_distSEXP);
    Rcpp::traits::input_parameter< double >::type error_sd(error_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_mapNegLogLik(map_dist, max_table_dist, min_table_dist, error_sd));
    return rcpp_result_gen;
END_RCPP
}
// ac_optimizationNegLogLik
double ac_optimizationNegLogLik(NumericMatrix max_table_dist, NumericMatrix min_table_dist, NumericMatrix ag_coords, NumericMatrix sr_coords, NumericMatrix na_vals, double error_sd);
RcppExport SEXP _Racmacs_ac_optimizationNegLogLik(SEXP max_table_distSEXP, SEXP min_table_distSEXP, SEXP ag_coordsSEXP, SEXP sr_coordsSEXP, SEXP na_valsSEXP, SEXP error_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type max_table_dist(max_table_distSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type min_table_dist(min_table_distSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ag_coords(ag_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sr_coords(sr_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type na_vals(na_valsSEXP);
    Rcpp::traits::input_parameter< double >::type error_sd(error_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_optimizationNegLogLik(max_table_dist, min_table_dist, ag_coords, sr_coords, na_vals, error_sd));
    return rcpp_result_gen;
END_RCPP
}
// ac_mapCoordNegLogLik
double ac_mapCoordNegLogLik(NumericVector coord_par, int num_ags, int num_sr, int num_dims, NumericMatrix max_table_dist, NumericMatrix min_table_dist, NumericMatrix na_vals, double error_sd);
RcppExport SEXP _Racmacs_ac_mapCoordNegLogLik(SEXP coord_parSEXP, SEXP num_agsSEXP, SEXP num_srSEXP, SEXP num_dimsSEXP, SEXP max_table_distSEXP, SEXP min_table_distSEXP, SEXP na_valsSEXP, SEXP error_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coord_par(coord_parSEXP);
    Rcpp::traits::input_parameter< int >::type num_ags(num_agsSEXP);
    Rcpp::traits::input_parameter< int >::type num_sr(num_srSEXP);
    Rcpp::traits::input_parameter< int >::type num_dims(num_dimsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type max_table_dist(max_table_distSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type min_table_dist(min_table_distSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type na_vals(na_valsSEXP);
    Rcpp::traits::input_parameter< double >::type error_sd(error_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_mapCoordNegLogLik(coord_par, num_ags, num_sr, num_dims, max_table_dist, min_table_dist, na_vals, error_sd));
    return rcpp_result_gen;
END_RCPP
}
// calc_coord_dist
NumericVector calc_coord_dist(NumericMatrix coords1, NumericMatrix coords2);
RcppExport SEXP _Racmacs_calc_coord_dist(SEXP coords1SEXP, SEXP coords2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords1(coords1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords2(coords2SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_coord_dist(coords1, coords2));
    return rcpp_result_gen;
END_RCPP
}
// euc_dist
double euc_dist(NumericVector coords1, NumericVector coords2);
RcppExport SEXP _Racmacs_euc_dist(SEXP coords1SEXP, SEXP coords2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coords1(coords1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coords2(coords2SEXP);
    rcpp_result_gen = Rcpp::wrap(euc_dist(coords1, coords2));
    return rcpp_result_gen;
END_RCPP
}
// ac_mapDists
NumericMatrix ac_mapDists(NumericMatrix ag_coords, NumericMatrix sr_coords);
RcppExport SEXP _Racmacs_ac_mapDists(SEXP ag_coordsSEXP, SEXP sr_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ag_coords(ag_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sr_coords(sr_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_mapDists(ag_coords, sr_coords));
    return rcpp_result_gen;
END_RCPP
}
// ac_pointStress
double ac_pointStress(double map_dist, double table_dist, bool less_than);
RcppExport SEXP _Racmacs_ac_pointStress(SEXP map_distSEXP, SEXP table_distSEXP, SEXP less_thanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type map_dist(map_distSEXP);
    Rcpp::traits::input_parameter< double >::type table_dist(table_distSEXP);
    Rcpp::traits::input_parameter< bool >::type less_than(less_thanSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_pointStress(map_dist, table_dist, less_than));
    return rcpp_result_gen;
END_RCPP
}
// ac_coordStress
double ac_coordStress(NumericVector map_dist, NumericVector table_dist, LogicalVector less_than);
RcppExport SEXP _Racmacs_ac_coordStress(SEXP map_distSEXP, SEXP table_distSEXP, SEXP less_thanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type map_dist(map_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type table_dist(table_distSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type less_than(less_thanSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_coordStress(map_dist, table_dist, less_than));
    return rcpp_result_gen;
END_RCPP
}
// ac_optimizationStress
double ac_optimizationStress(NumericMatrix table_dist, NumericMatrix ag_coords, NumericMatrix sr_coords, NumericMatrix lessthans, NumericMatrix morethans, NumericMatrix na_vals);
RcppExport SEXP _Racmacs_ac_optimizationStress(SEXP table_distSEXP, SEXP ag_coordsSEXP, SEXP sr_coordsSEXP, SEXP lessthansSEXP, SEXP morethansSEXP, SEXP na_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type table_dist(table_distSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ag_coords(ag_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sr_coords(sr_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lessthans(lessthansSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type morethans(morethansSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type na_vals(na_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_optimizationStress(table_dist, ag_coords, sr_coords, lessthans, morethans, na_vals));
    return rcpp_result_gen;
END_RCPP
}
// grid_search
NumericVector grid_search(NumericMatrix test_coords, NumericMatrix pair_coords, NumericVector table_dist, NumericVector lessthans, NumericVector morethans, NumericVector na_vals);
RcppExport SEXP _Racmacs_grid_search(SEXP test_coordsSEXP, SEXP pair_coordsSEXP, SEXP table_distSEXP, SEXP lessthansSEXP, SEXP morethansSEXP, SEXP na_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type test_coords(test_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pair_coords(pair_coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type table_dist(table_distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lessthans(lessthansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type morethans(morethansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type na_vals(na_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_search(test_coords, pair_coords, table_dist, lessthans, morethans, na_vals));
    return rcpp_result_gen;
END_RCPP
}
// ac_mapCoordStress
double ac_mapCoordStress(NumericVector coord_par, int num_ags, int num_sr, int num_dims, NumericMatrix table_dist, NumericMatrix lessthans, NumericMatrix morethans, NumericMatrix na_vals);
RcppExport SEXP _Racmacs_ac_mapCoordStress(SEXP coord_parSEXP, SEXP num_agsSEXP, SEXP num_srSEXP, SEXP num_dimsSEXP, SEXP table_distSEXP, SEXP lessthansSEXP, SEXP morethansSEXP, SEXP na_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type coord_par(coord_parSEXP);
    Rcpp::traits::input_parameter< int >::type num_ags(num_agsSEXP);
    Rcpp::traits::input_parameter< int >::type num_sr(num_srSEXP);
    Rcpp::traits::input_parameter< int >::type num_dims(num_dimsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type table_dist(table_distSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lessthans(lessthansSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type morethans(morethansSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type na_vals(na_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(ac_mapCoordStress(coord_par, num_ags, num_sr, num_dims, table_dist, lessthans, morethans, na_vals));
    return rcpp_result_gen;
END_RCPP
}
// convert2logCpp
Rcpp::List convert2logCpp(StringMatrix titers);
RcppExport SEXP _Racmacs_convert2logCpp(SEXP titersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringMatrix >::type titers(titersSEXP);
    rcpp_result_gen = Rcpp::wrap(convert2logCpp(titers));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Racmacs_ac_pointLogLik", (DL_FUNC) &_Racmacs_ac_pointLogLik, 4},
    {"_Racmacs_ac_mapNegLogLik", (DL_FUNC) &_Racmacs_ac_mapNegLogLik, 4},
    {"_Racmacs_ac_optimizationNegLogLik", (DL_FUNC) &_Racmacs_ac_optimizationNegLogLik, 6},
    {"_Racmacs_ac_mapCoordNegLogLik", (DL_FUNC) &_Racmacs_ac_mapCoordNegLogLik, 8},
    {"_Racmacs_calc_coord_dist", (DL_FUNC) &_Racmacs_calc_coord_dist, 2},
    {"_Racmacs_euc_dist", (DL_FUNC) &_Racmacs_euc_dist, 2},
    {"_Racmacs_ac_mapDists", (DL_FUNC) &_Racmacs_ac_mapDists, 2},
    {"_Racmacs_ac_pointStress", (DL_FUNC) &_Racmacs_ac_pointStress, 3},
    {"_Racmacs_ac_coordStress", (DL_FUNC) &_Racmacs_ac_coordStress, 3},
    {"_Racmacs_ac_optimizationStress", (DL_FUNC) &_Racmacs_ac_optimizationStress, 6},
    {"_Racmacs_grid_search", (DL_FUNC) &_Racmacs_grid_search, 6},
    {"_Racmacs_ac_mapCoordStress", (DL_FUNC) &_Racmacs_ac_mapCoordStress, 8},
    {"_Racmacs_convert2logCpp", (DL_FUNC) &_Racmacs_convert2logCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Racmacs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
