# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ac_ag_names <- function(map) {
    .Call('_Racmacs_ac_ag_names', PACKAGE = 'Racmacs', map)
}

ac_get_ag_coords <- function(opt) {
    .Call('_Racmacs_ac_get_ag_coords', PACKAGE = 'Racmacs', opt)
}

ac_get_sr_coords <- function(opt) {
    .Call('_Racmacs_ac_get_sr_coords', PACKAGE = 'Racmacs', opt)
}

ac_set_ag_coords <- function(opt, coords) {
    .Call('_Racmacs_ac_set_ag_coords', PACKAGE = 'Racmacs', opt, coords)
}

ac_set_sr_coords <- function(opt, coords) {
    .Call('_Racmacs_ac_set_sr_coords', PACKAGE = 'Racmacs', opt, coords)
}

ac_align_optimization <- function(source_optimization, target_optimization) {
    .Call('_Racmacs_ac_align_optimization', PACKAGE = 'Racmacs', source_optimization, target_optimization)
}

ac_subset_map <- function(map, ags, sr) {
    .Call('_Racmacs_ac_subset_map', PACKAGE = 'Racmacs', map, ags, sr)
}

#' @export
ac_table_colbases <- function(titer_table, min_col_basis) {
    .Call('_Racmacs_ac_table_colbases', PACKAGE = 'Racmacs', titer_table, min_col_basis)
}

#' @export
ac_table_distances <- function(titer_table, colbases) {
    .Call('_Racmacs_ac_table_distances', PACKAGE = 'Racmacs', titer_table, colbases)
}

ac_dimension_test_map <- function(titer_table, dimensions_to_test, test_proportion, minimum_column_basis, column_bases_from_full_table, num_optimizations, method, maxit, dim_annealing) {
    .Call('_Racmacs_ac_dimension_test_map', PACKAGE = 'Racmacs', titer_table, dimensions_to_test, test_proportion, minimum_column_basis, column_bases_from_full_table, num_optimizations, method, maxit, dim_annealing)
}

#' @export
ac_merge_titers <- function(titers, sd_lim = 1.0) {
    .Call('_Racmacs_ac_merge_titers', PACKAGE = 'Racmacs', titers, sd_lim)
}

#' @export
ac_merge_titer_layers <- function(titer_layers) {
    .Call('_Racmacs_ac_merge_titer_layers', PACKAGE = 'Racmacs', titer_layers)
}

#' @export
ac_relaxOptimization <- function(tabledist_matrix, titertype_matrix, ag_coords, sr_coords, method = "L-BFGS-B", maxit = 10000L, check_gradient_fn = FALSE) {
    .Call('_Racmacs_ac_relaxOptimization', PACKAGE = 'Racmacs', tabledist_matrix, titertype_matrix, ag_coords, sr_coords, method, maxit, check_gradient_fn)
}

random_coords <- function(nrow, ndim, min, max) {
    .Call('_Racmacs_random_coords', PACKAGE = 'Racmacs', nrow, ndim, min, max)
}

#' @export
ac_runBoxedOptimization <- function(tabledist_matrix, titertype_matrix, num_dims, coord_boxsize, method = "L-BFGS-B", maxit = 1000L, dim_annealing = FALSE) {
    .Call('_Racmacs_ac_runBoxedOptimization', PACKAGE = 'Racmacs', tabledist_matrix, titertype_matrix, num_dims, coord_boxsize, method, maxit, dim_annealing)
}

#' @export
ac_runOptimizations <- function(titertable, colbases, num_dims, num_optimizations, method, maxit, dim_annealing) {
    .Call('_Racmacs_ac_runOptimizations', PACKAGE = 'Racmacs', titertable, colbases, num_dims, num_optimizations, method, maxit, dim_annealing)
}

#' @export
reduce_matrix_dimensions <- function(m, dim) {
    .Call('_Racmacs_reduce_matrix_dimensions', PACKAGE = 'Racmacs', m, dim)
}

#' @export
numeric_titers <- function(titers) {
    .Call('_Racmacs_numeric_titers', PACKAGE = 'Racmacs', titers)
}

#' @export
log_titers <- function(titers) {
    .Call('_Racmacs_log_titers', PACKAGE = 'Racmacs', titers)
}

#' @export
titer_types_int <- function(titers) {
    .Call('_Racmacs_titer_types_int', PACKAGE = 'Racmacs', titers)
}

ac_procrustes <- function(X, Xstar, translation, dilation) {
    .Call('_Racmacs_ac_procrustes', PACKAGE = 'Racmacs', X, Xstar, translation, dilation)
}

ac_align_coords <- function(source, target, translation = TRUE, dilation = FALSE) {
    .Call('_Racmacs_ac_align_coords', PACKAGE = 'Racmacs', source, target, translation, dilation)
}

euc_dist <- function(coords1, coords2) {
    .Call('_Racmacs_euc_dist', PACKAGE = 'Racmacs', coords1, coords2)
}

#' @export
ac_mapDists <- function(ag_coords, sr_coords) {
    .Call('_Racmacs_ac_mapDists', PACKAGE = 'Racmacs', ag_coords, sr_coords)
}

#' @export
ac_pointStress <- function(map_dist, table_dist, less_than) {
    .Call('_Racmacs_ac_pointStress', PACKAGE = 'Racmacs', map_dist, table_dist, less_than)
}

#' @export
ac_coordStress <- function(map_dist, table_dist, less_than) {
    .Call('_Racmacs_ac_coordStress', PACKAGE = 'Racmacs', map_dist, table_dist, less_than)
}

#' @export
grid_search <- function(test_coords, pair_coords, table_dist, lessthans, morethans, na_vals) {
    .Call('_Racmacs_grid_search', PACKAGE = 'Racmacs', test_coords, pair_coords, table_dist, lessthans, morethans, na_vals)
}

