# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ac_pointLogLik <- function(map_dist, max_table_dist, min_table_dist, error_sd) {
    .Call('_Racmacs_ac_pointLogLik', PACKAGE = 'Racmacs', map_dist, max_table_dist, min_table_dist, error_sd)
}

#' @export
ac_mapNegLogLik <- function(map_dist, max_table_dist, min_table_dist, error_sd) {
    .Call('_Racmacs_ac_mapNegLogLik', PACKAGE = 'Racmacs', map_dist, max_table_dist, min_table_dist, error_sd)
}

#' @export
ac_optimizationNegLogLik <- function(max_table_dist, min_table_dist, ag_coords, sr_coords, na_vals, error_sd) {
    .Call('_Racmacs_ac_optimizationNegLogLik', PACKAGE = 'Racmacs', max_table_dist, min_table_dist, ag_coords, sr_coords, na_vals, error_sd)
}

#' @export
ac_mapCoordNegLogLik <- function(coord_par, num_ags, num_sr, num_dims, max_table_dist, min_table_dist, na_vals, error_sd) {
    .Call('_Racmacs_ac_mapCoordNegLogLik', PACKAGE = 'Racmacs', coord_par, num_ags, num_sr, num_dims, max_table_dist, min_table_dist, na_vals, error_sd)
}

#' Calculate the distance between two sets of coordinates
#'
#' This calculates the euclidean distance, row by row, of two sets of coordinates.
#'
#' @export
calc_coord_dist <- function(coords1, coords2) {
    .Call('_Racmacs_calc_coord_dist', PACKAGE = 'Racmacs', coords1, coords2)
}

#' @export
euc_dist <- function(coords1, coords2) {
    .Call('_Racmacs_euc_dist', PACKAGE = 'Racmacs', coords1, coords2)
}

#' @export
ac_mapDists <- function(ag_coords, sr_coords) {
    .Call('_Racmacs_ac_mapDists', PACKAGE = 'Racmacs', ag_coords, sr_coords)
}

#' @export
ac_pointStress <- function(map_dist, table_dist, less_than) {
    .Call('_Racmacs_ac_pointStress', PACKAGE = 'Racmacs', map_dist, table_dist, less_than)
}

#' @export
ac_coordStress <- function(map_dist, table_dist, less_than) {
    .Call('_Racmacs_ac_coordStress', PACKAGE = 'Racmacs', map_dist, table_dist, less_than)
}

#' @export
ac_optimizationStress <- function(table_dist, ag_coords, sr_coords, lessthans, morethans, na_vals) {
    .Call('_Racmacs_ac_optimizationStress', PACKAGE = 'Racmacs', table_dist, ag_coords, sr_coords, lessthans, morethans, na_vals)
}

#' @export
grid_search <- function(test_coords, pair_coords, table_dist, lessthans, morethans, na_vals) {
    .Call('_Racmacs_grid_search', PACKAGE = 'Racmacs', test_coords, pair_coords, table_dist, lessthans, morethans, na_vals)
}

#' @export
ac_mapCoordStress <- function(coord_par, num_ags, num_sr, num_dims, table_dist, lessthans, morethans, na_vals) {
    .Call('_Racmacs_ac_mapCoordStress', PACKAGE = 'Racmacs', coord_par, num_ags, num_sr, num_dims, table_dist, lessthans, morethans, na_vals)
}

convert2logCpp <- function(titers) {
    .Call('_Racmacs_convert2logCpp', PACKAGE = 'Racmacs', titers)
}

